version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

jobs:
  build_staging:
    docker:
    - image: circleci/ruby:2.4.1-jessie
      environment:
        BUNDLE_WITHOUT: production
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        MYSQL_USER: root
        RACK_ENV: development
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: staging-hello-world

  build_prod:
    docker:
      - image: circleci/ruby:2.4.1-jessie
        environment:
          BUNDLE_WITHOUT: test:development
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RACK_ENV: production

    steps:
      - checkout
      - run:
          name: test_for_tag
          command: echo "$CIRCLE_TAG"

workflows:
  version: 2

  staging:
    jobs:
      - build_staging:
          filters:
            branches:
              only:
                - /^((?!master).)*$/

  production:
    jobs:
      - build_prod:
          filters:
            branches: 
              only: /^master$/

