version: 2.1
jobs:
  build_dev:
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_WITHOUT: production
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RACK_ENV: development
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
    steps:
      - checkout
      - run:
          name: which_bundler
          command: bundle -v
      - restore_cache:
          keys:
            - hello-world-{{ checksum "Gemfile.lock" }}
            - hello-world-
      - run:
          name: bundle_install
          command: bundle check || bundle install
      - save_cache:
          key: hello-world-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: 
          name: wait_for_db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: test_db_connectivity
          command: bundle exec rake db:create
      - run: echo "hello development"
  build_prod:
    docker:
      - image: ruby:2.4.0
    steps:
      - checkout
      - run: echo "hello production"
workflows:
  version: 2
  development:
    jobs:
      - build_dev:
          filters:
            branches:
              only:
                - /^((?!master).)*$/
  production:
    jobs:
      - build_prod:
          filters:
            branches:
              only: /^master$/

