development: &development
  adapter: mysql2
  host: 127.0.0.1 
  username: <%= ENV['MYSQL_USER'] || "" %>
  port: <%= ENV['MYSQL_PORT'] || "3306" %>
  database: dev
  local_infile: true

read_only_development:
  <<: *development
  database: readonly
  local_infile: true

test: &test
  adapter: mysql2
  host: 127.0.0.1
  port: <%= ENV['MYSQL_PORT'] %>
  database: test
  local_infile: true

read_only_test:
  <<: *test

production: &production
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: <%= ENV['RDS_POOL_SIZE'] || 50 %>
  local_infile: true

read_only_production:
  <<: *production
  database: <%= ENV['RDS_RO_DB_NAME'] || ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_RO_USERNAME'] || ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_RO_PASSWORD'] || ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_RO_HOSTNAME'] || ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_RO_PORT'] || ENV['RDS_PORT'] %>
  local_infile: true

