development: &development
  adapter: mysql2
  host: 127.0.0.1 
  username: <%= ENV['MYSQL_USER'] || "" %>
  port: <%= ENV['MYSQL_PORT'] || "3306" %>
  database: dev
  local_infile: true

test: &test
  adapter: mysql2
  host: 127.0.0.1
  username: <%= ENV['MYSQL_USER'] || "" %>
  port: <%= ENV['MYSQL_PORT'] || "3306" %>
  database: test
  local_infile: true

production: &production
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: <%= ENV['RDS_POOL_SIZE'] || 50 %>
  local_infile: true
